AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-sam

  Sample SAM Template for todo-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    CodeUri: todo/
    Environment:
      Variables:
          TODO_TABLE: !Ref ToDoTable
  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - "*"
      AllowHeaders:
        - "*"
      AllowMethods:
        - "*"
    Auth:
      Authorizers:
        OAuth2Authorizer:
          JwtConfiguration:
            issuer: "https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_s4syVYS6n"
            audience:
              - 60jvm1avgd6t55k4uc15dgu6iq
          IdentitySource: "$request.header.Authorization"
      DefaultAuthorizer: OAuth2Authorizer

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: helloworld.lambdaHandler
      Events:
        Method:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  ListToDosFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        Handler: listToDos.handler
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ToDoTable
        Events:
          Method:
            Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /todos
              Method: get
  GetToDoFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        Handler: getToDo.handler
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ToDoTable
        Events:
          Method:
            Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /todos/{id}
              Method: get
  UpdateToDoFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        Handler: updateToDo.handler
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ToDoTable
        Events:
          Method:
            Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /todos/{id}
              Method: put
  CreateToDoFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        Handler: createToDo.handler
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ToDoTable
        Events:
          Method:
            Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /todos/{id}
              Method: post
  DeleteToDoFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        Handler: deleteToDo.handler
        Policies:
          - DynamoDBCrudPolicy:
              TableName: !Ref ToDoTable
        Events:
          Method:
            Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /todos/{id}
              Method: delete
  ToDoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello"